const wordList = [
    "apple", "banana", "orange", "blueberry", "strawberry", "pineapple", "tomato", "potato", "watermelon", "melon", "peach", "pear", "apricot", "blackberry", "raspberry", "onion", "cauliflower", "pumpkin", "eggplant", "corn", "wheat", "garlic", "green bean", "beans", "kale", "parsnip", "rhubarb", "rice", "hot pepper", "bell pepper", "radish", "cabbage", "starfruit", "amaranth", "artichoke", "beet", "bok choy", "cranberry", "grape", "yam", "hashbrown", "berry", "bread", "baguette", "egg", "cheese", "salad", "omelet", "fish", "soup", "fruit", "vegetable", "food", "meal", "breakfast", "lunch", "dinner", "supper", "mushroom", "morel", "chanterelle", "pizza", "hotpot", "pancake", "waffle", "taco", "burrito", "fajitas", "bacon", "ham", "sausage", "porc", "steak", "beef", "cake", "pie", "cookie", "spaghetti", "sashimi", "maki", "sushi", "tortilla", "parmesan", "pudding", "jello", "ice cream", "cream", "sauce", "sutffing", "burger", "hot-dog", "treat", "candy", "dessert", "lollipop", "algae", "broth", "dip", "hazelnut", "cashew", "almond", "pistachio", "peanut", "pecan", "walnut", "macademia", "pepitas", "cobbler", "bruschetta", "coleslaw", "risotto", "muffin", "cupcake", "chowder", "stew", "escargot", "maple", "curry", "ravioli", "macaroni", "rigatoni", "spaghettini", "noodle", "vermicelli", "fusilli", "fettucine", "linguine", "lasagna", "farfalle", "orzo", "cannelloni", "tortellini", "pomegranate", "mango", "mayonnaise", "mustard", "cucumber", "sugar", "lemon", "lime", "grapefruit", "tangerine", "mandarine", "clementine", "nectarine", "kiwi", "dragonfruit", "passionfruit", "brussel sprouts", "avocado", "cantaloupe", "cherry", "coconut", "fig", "cocoa", "bagel", "basil", "cilantro", "pesto", "chili", "marinara",
    "tulip", "jazz", "poppy", "sunflower", "fairy rose", "cactus", "rose", "lily", "orchid", "daisy", "dandelion", "violet", "flower", "vine", "moss", "grass", "lavender", "bush", "tree", "oak", "pine", "sappling", "birch", "acacia", "spruce", "bamboo", "aloe vera",
    "coffee", "tea", "water", "milk", "milkshake", "mead", "beer", "wine", "whiskey", "vodka", "gin", "sake", "juice", "espresso", "syrup", "cocktail", "ginger ale", "oil", "vinegar",
    "trout", "salmon", "sardine", "squid", "calamari", "octopus", "blobfish", "tiger fish", "shark", "whale", "carp", "bass", "eel", "lobster", "crab", "bream", "founder", "sunfish", "sea cucumber", "clam", "crayfish", "mussel", "shrimp", "periwinkle", "snail", "stingray", "urchin",
    "spring", "summer", "fall", "autumn", "winter", "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "sunny", "rainy", "cloudy", "stormy", "sun", "rain", "cloud", "storm",
    "guitar", "violin", "drum", "flute", "harp", "trumpet", "saxophone", "xylophone", "piano", "maracas", "bell", "keyboard", "tambourine", "cymbal", "horn", "french horn", "trombone", "clarinet", "snare drum", "marimba", "electric guitar", "accoustic guitar", "banjo", "ukulele", "harmonica", "bass guitar", "tuba", "piccolo",
    "triangle", "circle", "square", "pentagon", "hexagon", "heptagon", "octagon", "diamond", "rectangle", "sphere", "cube", "cone", "cylinder", "prism", "cuboid",
    "red", "green", "blue", "white", "black", "gray", "grey", "purple", "turquoise", "teal", "pink", "brown", "magenta", "cyan", "yellow",
    "jungle", "desert", "plain", "mountain", "valley", "meadow", "taiga", "forest", "badland", "tundra", "swamp", "savannah", "beach", "shore", "river", "ocean", "lake", "aquatic", "grassland", "marine", "temperate", "plateau", "woodland", "tropical",
    "car", "truck", "scooter", "bicycle", "bike", "tricycle", "plane", "blimp", "hot air baloon", "helicopter", "crane", "motorcycle", "skateboard", "roller skates", "skates", "ice skates", "submarine", "boat", "sailboat", "rowboat", "jet ski", "fighter jet", "cargo plane", "aeroplane", "school bus", "bus", "train", "metro", "subway", "bullet train", "speed train", "cargo train", "segway", "hoverboard", "forklift", "paddle boat",
    "dog", "cat", "mouse", "rat", "hamster", "ferret", "bunny", "rabbit", "sperm whale", "ostrich", "chicken", "rooster", "hen", "pig", "duck", "mallard", "goose", "geese", "dinosaur", "cow", "bull", "sheep", "lamb", "goat", "moutain goat", "brown cow", "snake", "lizard", "dragon", "cameleon", "insect", "mammal", "aardvark", "wolf", "tiger", "lion", "panther", "leopard", "cheetah", "anteater", "sloth", "fox", "bear", "brown bear", "black bear", "white bear", "grizzly bear", "walrus", "sea lion", "panda", "worm", "kitten", "human", "horse", "cattle", "guinea pig", "frog", "bullfrod", "toad", "shepherd", "parrot", "bird", "skunk", "beaver", "porcupine", "hedgehog", "eagle", "hawk", "pigeon", "seagull", "foxhound", "mole", "python", "anaconda", "caterpillar", "cobra", "archerfish", "scorpion", "elephant", "beetle", "rhinoceros", "hippopotamus", "cockroach", "gecko", "axolotl", "penguin", "bee", "honey bee", "moth", "wasp", "malamute", "dolphin", "tropical fish", "robin", "anglerfish", "ape", "gorilla", "chimpanzee", "chihuahua", "rattlesake", "hornet", "catfish", "giant hornet", "hound", "husky", "pollock", "albatross", "tortoise", "turtle", "sea turtle", "boa", "tree boa", "anchovy", "hummingbird", "ant", "antelope", "hyena", "arctic fox", "tarantula", "cattle dog", "baboon", "badger", "bald eagle", "lynx", "spider", "arachnid", "owl", "bat", "fruit bat", "fireworm", "bed bugs", "canary", "sheepdog", "picard", "bison", "bloodhound", "griffon", "bandicoot", "swallow", "tiger shark", "great white shark", "hammerhead shark", "beagle", "vulture", "booby", "brown booby", "butterfly", "camel", "dromadaire", "barnacle", "basilisk", "bearded dragon", "chickadee", "iguana", "bobcat", "killer whale", "buffalo", "bullfrog", "butterfly fish", "bumblebee", "cricket", "capybara", "platypus", "centipede", "chipmunk", "squirrel", "raccoon", "clownfish", "house spider", "daddy long legs", "crab spider", "cuttlefish", "caribou", "moose", "deer", "white tailed deer", "viper", "alligator", "crocodile", "jellyfish", "kingsnake", "king cobra", "condor", "capuchin", "carpenter ant", "paddlefish", "sparrow", "cockatoo", "magpie", "raven", "cougar", "monkey", "woodpecker", "dragonfly", "dodo", "golden retriever", "elk", "seal", "starfish", "anemone", "falcon", "flamingo", "firefly", "fire eel", "flea", "salamander", "flying squirrel", "lemur", "meerkat", "bulldog", "giraffe", "toucan", "giant spider", "land snail", "grasshopper", "jackal", "tigerfish", "black mamba", "monster", "heron", "fowl", "tick", "hellbender", "horned beetle", "horseshoe crab", "hyna", "halibut", "hermit crab", "inchworm", "jumping spider", "kangaroo", "king rat snake", "ladybug", "lemming", "llama", "alpaca", "maggot", "manatee", "marmoset", "megalodon", "mollusk", "mosquito", "mule", "donkey", "macaw", "millipede", "narwhal", "needlefish", "opossum", "mammoth", "otter", "sea otter", "walrus",
    "doctor", "nurse", "mechanic", "pilot", "carpenter", "engineer", "software engineer", "architect", "social worker", "worker", "road worker", "security", "agent", "security agent", "princial", "teacher", "college teacher", "university teacher", "glass blower", "driver", "racecar driver", "student", "medical doctor", "philosopher", "warden", "inmate", "guard", "security guard", "officer", "police officer", "chief",
    "hospital", "college", "university", "restaurant", "house", "home", "office", "store", "shop", "jewelry store", "electronics store",
    "mathematics", "english", "french", "philosophy", "astronomy", "astrology", "science", "ethics", "sociology", "physical education", "education", "author", "writer", "publisher", "editor", "fashion designer", "designer", "marketer", "web design", "graphic design", "architecture",
    "arm", "leg", "head", "body", "torso", "hip", "waist", "butt", "foot", "feet", "hand", "fingers", "toes", "fingernail", "toenail", "thumb", "index", "shoulder", "forearm", "weenis", "elbow", "knee", "thigh", "calf", "heel", "achilles heel", "tendon", "finger", "toe", "ankle", "femur", "ears", "nose", "eyes", "forehead", "mouth", "lips", "penis", "labia", "vagina", "butt hole", "back", "stomach", "liver", "kidney", "lung", "heart", "intestines", "bladder", "bowel", "appendix", "bones", "bone", "muscle", "muscles", "body parts", "brain", "hair", "body hair", "eyebrow", "eyelash", "iris", "pupil", "eyeball", "nose hair", "beard", "facial hair", "wrist", "teeth", "tooth", "tongue", "throat", "neck", "collar bone", "nostril", "sinus", "balls", "testicles", "eurthra", "cervix", "uterus", "placenta", "esophagus", "pharynx", "larynx", "pancreas", "prostate",
    "qi",
    //
];
let wordLength = [{length: 2, count: 0}, {length: 3, count: 0}, {length: 4, count: 0}, {length: 5, count: 0}, {length: 6, count: 0}, {length: 7, count: 0}, {length: 8, count: 0}, {length: 9, count: 0}, {length: 10, count: 0}, {length: 11, count: 0}, {length: 12, count: 0}, {length: 13, count: 0}, {length: 14, count: 0}, {length: 15, count: 0}, {length: 16, count: 0}, {length: 17, count: 0}, {length: 18, count: 0}, {length: 19, count: 0}, {length: 20, count: 0}];
let wordCount = [{words: 1, count: 0}, {words: 2, count: 0}, {words: 3, count: 0}];

console.log(`${wordList.length} words`);

//Checks for duplicates and counts
for(let i = 0; i < wordList.length; i++){
    for(let j = 0; j < wordList.length; j++){
        if(wordList[i] == wordList[j] && i != j){
            console.log(`"${wordList[i]}" is a duplicate at word ${i}`);
        }
    }

    wordLength[wordList[i].length - 2].count++;
    wordCount[wordList[i].split(" ").length - 1].count++;
}

//console.table(wordLength);
//console.table(wordCount);